local mod = get_mod("Gromril Fart SFX")
mod:echo("[Impenetrable Fart Sound] loaded")
mod:hook_safe(StateIngame, "update", function(...)
    Wwise.load_bank("wwise/Play_career_ability_bardin_ironbreaker_enter")
    WwiseWorld.trigger_event(Wwise.wwise_world(Managers.world:world("level_world")), Play_career_ability_bardin_ironbreaker_enter)
end)
mod:command("fart_sound", "", function()
    local sound = WwiseWorld.trigger_event(Wwise.wwise_world(Managers.world:world("level_world")), "Play_career_ability_bardin_ironbreaker_enter")
end)